#!/usr/bin/env bash
set -euo pipefail

SITE_FILE="/etc/nginx/sites-available/cwscx-staging"
LINK_FILE="/etc/nginx/sites-enabled/cwscx-staging"

SERVER_NAME="${SERVER_NAME:-cwscx-tst01.cwsey.com}"
SSL_CERTIFICATE="${SSL_CERTIFICATE:-/etc/ssl/cwscx/cwscx.crt}"
SSL_CERTIFICATE_KEY="${SSL_CERTIFICATE_KEY:-/etc/ssl/cwscx/cwscx.key}"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root (sudo bash scripts/linux/deploy_nginx.sh)"
  exit 1
fi

# Remove conflicting enabled site configs that declare the same server_name.
for enabled_conf in /etc/nginx/sites-enabled/*; do
  [[ -e "${enabled_conf}" ]] || continue
  if [[ "$(readlink -f "${enabled_conf}")" == "$(readlink -f "${LINK_FILE}")" ]]; then
    continue
  fi
  if grep -Eq "server_name\s+.*\b${SERVER_NAME}\b" "${enabled_conf}"; then
    echo "Disabling conflicting nginx site config: ${enabled_conf}"
    rm -f "${enabled_conf}"
  fi
done

cat >"${SITE_FILE}" <<EOF
####################################################################
# NOTE: This file is generated by /opt/cwscx/scripts/linux/deploy_nginx.sh
#
# Routes:
# - /                         -> Mystery Shopper SPA (public)
# - /dashboard/               -> Dashboard SPA (internal)
# - /surveys/b2b/             -> B2B Surveys SPA (internal)
# - /surveys/installation/    -> Installation Surveys SPA (internal)
# - /api/*                    -> FastAPI backend (http://127.0.0.1:8000)
####################################################################

# =========================
# HTTP -> HTTPS redirect
# =========================
server {
    listen 80;
    server_name ${SERVER_NAME};

    return 301 https://\$host\$request_uri;
}

# =========================
# HTTPS server
# =========================
server {
    listen 443 ssl;
    server_name ${SERVER_NAME};

    ssl_certificate ${SSL_CERTIFICATE};
    ssl_certificate_key ${SSL_CERTIFICATE_KEY};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # -------------------------
    # API -> FastAPI (strip /api)
    # -------------------------
    location /api/ {
        proxy_pass http://127.0.0.1:8000/;

        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_connect_timeout 10s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;
    }

    # Root: serves mystery shopper SPA
    location ^~ /assets/ {
        alias /opt/cwscx/frontends-src/public/mystery-shopper/dist/assets/;
        try_files \$request_filename =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        alias /opt/cwscx/frontends-src/public/mystery-shopper/dist/;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    # Canonical trailing-slash redirects for SPAs
    location = /dashboard {
        return 301 /dashboard/;
    }

    location = /surveys {
        return 301 /surveys/;
    }

    location = /surveys/b2b {
        return 301 /surveys/b2b/;
    }

    location = /surveys/installation {
        return 301 /surveys/installation/;
    }

    # Dashboard SPA
    location ^~ /dashboard/assets/ {
        alias /opt/cwscx/frontends-src/dashboard/dist/assets/;
        try_files \$uri =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /dashboard/ {
        alias /opt/cwscx/frontends-src/dashboard/dist/;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        try_files \$uri \$uri/ /dashboard/index.html;
    }

    location = /dashboard/index.html {
        alias /opt/cwscx/frontends-src/dashboard/dist/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    # Surveys: B2B SPA
    location ^~ /surveys/b2b/assets/ {
        alias /opt/cwscx/frontends-src/internal-surveys/b2b/dist/assets/;
        try_files \$uri =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /surveys/b2b/ {
        alias /opt/cwscx/frontends-src/internal-surveys/b2b/dist/;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        try_files \$uri \$uri/ /surveys/b2b/index.html;
    }

    location = /surveys/b2b/index.html {
        alias /opt/cwscx/frontends-src/internal-surveys/b2b/dist/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    # Surveys: Installation SPA
    location ^~ /surveys/installation/assets/ {
        alias /opt/cwscx/frontends-src/internal-surveys/installation/dist/assets/;
        try_files \$uri =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /surveys/installation/ {
        alias /opt/cwscx/frontends-src/internal-surveys/installation/dist/;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        try_files \$uri \$uri/ /surveys/installation/index.html;
    }

    location = /surveys/installation/index.html {
        alias /opt/cwscx/frontends-src/internal-surveys/installation/dist/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    # Optional convenience redirect
    location = /surveys/ {
        return 302 /surveys/b2b/;
    }

    # Future: mystery shopper surveys SPA
    # location /surveys/mystery-shopper/ {
    #     alias /opt/cwscx/frontends-src/public/mystery-shopper/dist/;
    #     index index.html;
    #     try_files \$uri \$uri/ /surveys/mystery-shopper/index.html;
    # }
}
EOF

ln -sf "${SITE_FILE}" "${LINK_FILE}"
nginx -t
systemctl restart nginx

echo "Nginx deployment complete."
