#!/usr/bin/env bash
set -euo pipefail

SITE_NAME="${SITE_NAME:-cwscx-staging}"
SITE_FILE="/etc/nginx/sites-available/${SITE_NAME}"
LINK_FILE="/etc/nginx/sites-enabled/${SITE_NAME}"
SNIPPETS_DIR="/etc/nginx/snippets"
EXTRA_ROUTES_FILE="${SNIPPETS_DIR}/${SITE_NAME}-extra-routes.conf"

SERVER_NAME="${SERVER_NAME:-cwscx-tst01.cwsey.com}"
SSL_CERTIFICATE="${SSL_CERTIFICATE:-/etc/ssl/cwscx/cwscx.crt}"
SSL_CERTIFICATE_KEY="${SSL_CERTIFICATE_KEY:-/etc/ssl/cwscx/cwscx.key}"
PGADMIN_HOST="${PGADMIN_HOST:-127.0.0.1}"
PGADMIN_PORT="${PGADMIN_PORT:-5051}"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root (sudo bash scripts/linux/deploy_nginx.sh)"
  exit 1
fi

mkdir -p "${SNIPPETS_DIR}"

seed_staging_extra_routes() {
  if [[ "${SITE_NAME}" != "cwscx-staging" ]]; then
    return 0
  fi

  if [[ -f "${EXTRA_ROUTES_FILE}" ]]; then
    echo "Preserving existing staging extra routes: ${EXTRA_ROUTES_FILE}"
    return 0
  fi

  cat >"${EXTRA_ROUTES_FILE}" <<'EOF'
location = /system-check {
    return 301 /system-check/;
}

location ^~ /system-check/api/ {
    proxy_pass http://127.0.0.1:8010/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300;
    proxy_connect_timeout 60;
    proxy_send_timeout 300;
}

location ^~ /system-check/assets/ {
    alias /opt/system-check-platform/current/frontend/dist/assets/;
    access_log off;
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
}

location = /system-check/server-check.png {
    alias /opt/system-check-platform/current/frontend/dist/server-check.png;
    access_log off;
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
}

location = /system-check/index.html {
    alias /opt/system-check-platform/current/frontend/dist/index.html;
    add_header Cache-Control "no-store";
}

location /system-check/ {
    alias /opt/system-check-platform/current/frontend/dist/;
    try_files $uri $uri/ /system-check/index.html;
    add_header Cache-Control "no-store";
}
EOF

  echo "Created staging extra routes snippet: ${EXTRA_ROUTES_FILE}"
}

seed_staging_extra_routes

# Remove conflicting enabled site configs that declare the same server_name.
for enabled_conf in /etc/nginx/sites-enabled/*; do
  [[ -e "${enabled_conf}" ]] || continue
  if [[ "$(readlink -f "${enabled_conf}")" == "$(readlink -f "${LINK_FILE}")" ]]; then
    continue
  fi
  if grep -Eq "server_name\s+.*\b${SERVER_NAME}\b" "${enabled_conf}"; then
    echo "Disabling conflicting nginx site config: ${enabled_conf}"
    rm -f "${enabled_conf}"
  fi
done

cat >"${SITE_FILE}" <<EOF
####################################################################
# NOTE: This file is generated by /opt/cwscx/scripts/linux/deploy_nginx.sh
#
# Routes:
# - /                         -> Redirect to dashboard
# - /dashboard/               -> Dashboard SPA (internal)
# - /surveys/b2b/             -> B2B Surveys SPA (internal)
# - /surveys/installation/    -> Installation Surveys SPA (internal)
# - /surveys/mystery-shopper/ -> Mystery Shopper Surveys SPA (internal)
# - /pgadmin/                 -> pgAdmin (proxied container)
# - /api/*                    -> FastAPI backend (http://127.0.0.1:8000)
####################################################################

# =========================
# HTTP -> HTTPS redirect
# =========================
server {
    listen 80;
    server_name ${SERVER_NAME};

    return 301 https://\$host\$request_uri;
}

# =========================
# HTTPS server
# =========================
server {
    listen 443 ssl;
    server_name ${SERVER_NAME};

    ssl_certificate ${SSL_CERTIFICATE};
    ssl_certificate_key ${SSL_CERTIFICATE_KEY};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # -------------------------
    # API -> FastAPI (strip /api)
    # -------------------------
    location /api/ {
        proxy_pass http://127.0.0.1:8000/;

        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_connect_timeout 30s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        send_timeout 300s;
    }

    # Root
    location = /favicon.ico {
        add_header Cache-Control "public, max-age=300";
        return 204;
    }

    location / {
        return 301 /dashboard/;
    }

    # Canonical trailing-slash redirects for SPAs
    location = /dashboard {
        return 301 /dashboard/;
    }

    location = /surveys {
        return 301 /surveys/;
    }

    location = /surveys/b2b {
        return 301 /surveys/b2b/;
    }

    location = /surveys/installation {
        return 301 /surveys/installation/;
    }

    location = /surveys/mystery-shopper {
        return 301 /surveys/mystery-shopper/;
    }

    location = /pgadmin {
        return 301 /pgadmin/;
    }

    # Extra staging-only or environment-specific routes can live here without
    # being overwritten on each CWSCX deploy.
    include ${EXTRA_ROUTES_FILE};

    # Dashboard SPA
    location ^~ /dashboard/assets/ {
        alias /opt/cwscx/frontends-src/dashboard/dist/assets/;
        try_files \$uri =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /dashboard/ {
        alias /opt/cwscx/frontends-src/dashboard/dist/;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        try_files \$uri \$uri/ /dashboard/index.html;
    }

    location = /dashboard/index.html {
        alias /opt/cwscx/frontends-src/dashboard/dist/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    # Surveys: B2B SPA
    location ^~ /surveys/b2b/assets/ {
        alias /opt/cwscx/frontends-src/internal-surveys/b2b/dist/assets/;
        try_files \$uri =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /surveys/b2b/ {
        alias /opt/cwscx/frontends-src/internal-surveys/b2b/dist/;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        try_files \$uri \$uri/ /surveys/b2b/index.html;
    }

    location = /surveys/b2b/index.html {
        alias /opt/cwscx/frontends-src/internal-surveys/b2b/dist/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    # Surveys: Installation SPA
    location ^~ /surveys/installation/assets/ {
        alias /opt/cwscx/frontends-src/internal-surveys/installation/dist/assets/;
        try_files \$uri =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /surveys/installation/ {
        alias /opt/cwscx/frontends-src/internal-surveys/installation/dist/;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        try_files \$uri \$uri/ /surveys/installation/index.html;
    }

    location = /surveys/installation/index.html {
        alias /opt/cwscx/frontends-src/internal-surveys/installation/dist/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    # Surveys: Mystery Shopper SPA
    location ^~ /surveys/mystery-shopper/assets/ {
        alias /opt/cwscx/frontends-src/public/mystery-shopper/dist/assets/;
        try_files \$uri =404;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /surveys/mystery-shopper/ {
        alias /opt/cwscx/frontends-src/public/mystery-shopper/dist/;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        try_files \$uri \$uri/ /surveys/mystery-shopper/index.html;
    }

    location = /surveys/mystery-shopper/index.html {
        alias /opt/cwscx/frontends-src/public/mystery-shopper/dist/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    # pgAdmin container
    location /pgadmin/ {
        proxy_pass http://${PGADMIN_HOST}:${PGADMIN_PORT};

        proxy_set_header Host \$host;
        proxy_set_header X-Script-Name /pgadmin;
        proxy_set_header X-Scheme \$scheme;

        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;

        proxy_connect_timeout 30s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        send_timeout 300s;
    }

    # Optional convenience redirect
    location = /surveys/ {
        return 302 /surveys/b2b/;
    }

}
EOF

ln -sf "${SITE_FILE}" "${LINK_FILE}"
nginx -t
systemctl restart nginx

echo "Nginx deployment complete."
