"""Reliable PDF report generation using reportlab canvas API."""

from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from typing import Any


def render_report_pdf(payload: dict[str, Any], generated_by: str) -> bytes:
    """Generate PDF report with all data from payload."""
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    page_width, page_height = A4
    left_margin = 15
    top_margin = 30
    line_height = 14
    col_width = (page_width - 2 * left_margin) / 2

    y = page_height - top_margin

    def add_line(text: str = "", font_size: int = 10, bold: bool = False, spacing_after: int = 0):
        """Add a line of text and handle page breaks."""
        nonlocal y

        if font_size > 0:
            font = "Helvetica-Bold" if bold else "Helvetica"
            c.setFont(font, font_size)
            c.setFillColor(colors.black)

            # Wrap long text
            text = str(text)[:120]
            c.drawString(left_margin, y, text)

        y -= (line_height + spacing_after)

        if y < top_margin:
            c.showPage()
            y = page_height - top_margin

    filters = payload.get("filters", {})
    summary = payload.get("summary", {})
    comparison = payload.get("analytics_comparison", {})
    action_points = payload.get("action_points", [])
    business_breakdown = payload.get("business_breakdown", [])
    survey_questions = payload.get("survey_question_details", [])

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.HexColor("#0056A1"))
    c.drawString(left_margin, y, "Cable & Wireless — CWSCX B2B Report")
    y -= 25

    # Report type and generator
    add_line()
    report_type = filters.get("report_type", "unknown").replace("-", " ").title()
    add_line(f"Type: {report_type}", 11, True)
    add_line(f"Survey: {filters.get('survey_type', 'B2B')}", 10)
    add_line(f"Generated by: {generated_by}", 9)
    add_line(spacing_after=5)

    # Summary section
    add_line("Summary", 12, True, spacing_after=3)
    add_line(f"Total Visits: {summary.get('total_visits', 0)}")
    add_line(f"Total Businesses: {summary.get('total_businesses', 0)}")
    add_line(f"Total Responses: {summary.get('total_responses', 0)}")
    add_line(f"Average Score: {summary.get('average_score', 'N/A')}")
    add_line(spacing_after=5)

    # KPI Metrics
    if comparison:
        add_line("Key Performance Indicators", 12, True, spacing_after=3)
        for metric, label in [("nps", "NPS"), ("csat", "CSAT"), ("relationship_score", "Relationship")]:
            vals = comparison.get(metric, {})
            sel = vals.get("selected", "--")
            ovr = vals.get("overall", "--")
            add_line(f"{label}: {sel} (overall: {ovr})")
        add_line(spacing_after=5)

    # Survey Context
    selected_visit = payload.get("selected_visit_info", {})
    if selected_visit:
        add_line("Survey Context", 12, True, spacing_after=3)
        add_line(f"Business: {selected_visit.get('business_name', '--')}")
        add_line(f"Survey Date: {selected_visit.get('visit_date', '--')}")
        add_line(f"Status: {selected_visit.get('status', '--')}")
        add_line(f"Account Executive: {selected_visit.get('account_executive_name', '--')}")
        add_line(f"Representative: {selected_visit.get('representative_name', '--')}")
        team_members = selected_visit.get('team_member_names', [])
        if team_members:
            add_line(f"Team Members: {', '.join(team_members)}")
        add_line(spacing_after=5)

    # Category Breakdown
    category_comparison = payload.get("category_comparison", [])
    if category_comparison:
        add_line("Category Score Breakdown", 12, True, spacing_after=3)
        for item in category_comparison[:10]:
            cat = item.get('category', '--')
            sel_avg = item.get('selected_average_score', '--')
            ovr_avg = item.get('overall_average_score', '--')
            add_line(f"{cat}: {sel_avg} (overall: {ovr_avg})")
        add_line(spacing_after=5)

    # Action Points
    if action_points:
        outstanding = [a for a in action_points if a.get("action_status") != "Completed"]
        completed = [a for a in action_points if a.get("action_status") == "Completed"]

        if outstanding or completed:
            add_line("Action Points", 12, True, spacing_after=3)

            if outstanding:
                add_line(f"Outstanding ({len(outstanding)})", 11, True)
                for item in outstanding[:8]:
                    qnum = item.get("question_id", "--")
                    biz = item.get('business_name', '--')
                    action = item.get('action_required', '--')[:50]
                    owner = item.get('action_owner', '--')
                    timeframe = item.get('action_timeframe', '--')
                    add_line(f"  {biz}: Q{qnum} - {action}", 9)
                    add_line(f"    Owner: {owner}, Timeline: {timeframe}", 8)
                add_line(spacing_after=3)

            if completed:
                add_line(f"Completed ({len(completed)})", 11, True)
                for item in completed[:5]:
                    qnum = item.get("question_id", "--")
                    biz = item.get('business_name', '--')
                    action = item.get('action_required', '--')[:50]
                    timeframe = item.get('action_timeframe', '--')
                    add_line(f"  {biz}: Q{qnum} - {action}", 9)
                    add_line(f"    Timeline: {timeframe}", 8)

            add_line(spacing_after=5)

    # Business Breakdown
    if business_breakdown:
        add_line("Business Summary", 12, True, spacing_after=3)
        for item in business_breakdown[:10]:
            add_line(f"{item.get('business_name', '--')}: {item.get('visit_count', 0)} visits, Avg: {item.get('avg_score', 'N/A')}", 9)
        add_line(spacing_after=5)

    # Survey Responses
    if survey_questions:
        add_line("Survey Responses", 12, True, spacing_after=3)
        for item in survey_questions[:15]:
            qnum = item.get("question_number", "--")
            question = item.get("question_text", "--")[:60]
            answer = item.get("answer_text") or (f"{item.get('score')}/{item.get('score_max')}" if item.get("score") else "--")
            verbatim = item.get("verbatim", "")

            add_line(f"Q{qnum}: {question}", 9, bold=True)
            add_line(f"  Answer: {answer}", 8)
            if verbatim:
                add_line(f"  Verbatim: {verbatim[:80]}", 8)
        add_line(spacing_after=5)

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    footer_text = f"Report: {filters.get('survey_type', 'B2B')} | {report_type}"
    c.drawString(left_margin, 15, footer_text)

    c.save()
    pdf_bytes = buffer.getvalue()

    if not pdf_bytes or len(pdf_bytes) == 0:
        raise ValueError("PDF generation failed - no output")

    return pdf_bytes
